services:
  spring-boot-app:
    build:
      context: spring-boot-service
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: activities_db
      POSTGRES_USER: postgres
      # TODO: No one should hardcode passwords in the code. This is just for demo purposes. (for production, use secrets)
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  vue-app:
    build:
      context: vue-frontend
    ports:
      - "8081:8080"

volumes:
  db-data:
