version: '3'
services:
  spring-boot-app:
    build:
      context: spring-boot-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/activities_db
      SPRING_DATASOURCE_USERNAME: postgres
      # TODO: No one should hardcode passwords in the code. This is just for demo purposes. (for production, use secrets)
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_ENABLED: true
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: activities_db
      POSTGRES_USER: postgres
      # TODO: No one should hardcode passwords in the code. This is just for demo purposes. (for production, use secrets)
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  vue-app:
    build:
      context: vue-frontend
    ports:
      - "8081:8080"

volumes:
  postgres-data:
