spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}

  jpa:
    hibernate:
      ddl-auto: none
